name : "Deploy to production"
on:
    push:
        branches:
            - "production"

jobs:
    redeploy_everything:
        name: Deploying everything to production cluster
        runs-on: ubuntu-latest
        steps:
            - name: SSH into server
              uses: actions/checkout@v3
